CREATE TABLE STUDY (
                       ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       NAME VARCHAR(255) NOT NULL,
                       DESCRIPTION VARCHAR(500)
);

-- Optional: Insert a seed row
INSERT INTO STUDY (NAME, DESCRIPTION)
VALUES ('Demo Study', 'This is a test study for Flyway migration validation');
