CREATE TABLE STUDY (
                       ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       NAME VARCHAR2(255 CHAR) NOT NULL,
                       DESCRIPTION VARCHAR2(500 CHAR)
);

-- Optional: seed row
INSERT INTO STUDY (NAME, DESCRIPTION)
VALUES ('Demo Study', 'This is a test study for Flyway migration validation');
